# Tensor Products of Vectors

## Importing NumPy

We will need to import NumPy for tensor products. 

In [1]:
import numpy as np

## Introduction

One of the most common tensor products we will encounter throughout the following chapters of the book will be the tensor product of two qubits, which are represented by $2$-dimensional vector which have length (or "norm") $1$.

The general rule for the tensor product of two $2$-dimensional vectors is as follows:

\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} = 
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_2 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_2b_1 \\ a_2b_2
\end{pmatrix}
\end{align}

Here is a numerical example:

\begin{align}
\begin{pmatrix}
2 \\ 5
\end{pmatrix} \otimes 
\begin{pmatrix}
3 \\ 1
\end{pmatrix} = 
\begin{pmatrix}
2 \begin{pmatrix}
3 \\ 1
\end{pmatrix} \\ 5 \begin{pmatrix}
3 \\ 1
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
2 \cdot 3 \\ 2 \cdot 1 \\ 5 \cdot 3 \\ 5 \cdot 1
\end{pmatrix} = 
\begin{pmatrix}
6 \\ 2 \\ 15 \\ 5
\end{pmatrix}
\end{align}

For an example using Python we will use the "np.kron()" function, which is the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product), 

> "In mathematics, the Kronecker product, sometimes denoted by ⊗, is an operation on two matrices of arbitrary size resulting in a block matrix. It is a generalization of the outer product (which is denoted by the same symbol) from vectors to matrices, and gives the matrix of the tensor product with respect to a standard choice of basis. The Kronecker product should not be confused with the usual matrix multiplication, which is an entirely different operation."

In [2]:
# Define two ket-vectors

A = np.array([[2], 
              [5]])

B = np.array([[3],
              [1]])

# Take the Kronecker (tensor) product of the two column vectors
np.kron(A,B)

array([[ 6],
       [ 2],
       [15],
       [ 5]])

We can also define these two vectors as matrices which will allow us to compute Hermitian conjugates. The Kronecker product function 'np.kron()' will work all the same:

In [3]:
# Define the ket-vectors as 2x1 column matrices:
ket_A = np.matrix([[2], 
                   [5]])

ket_B = np.matrix([[3], 
                   [1]])

# Compute their Kronecker product
np.kron(ket_A, ket_B)

matrix([[ 6],
        [ 2],
        [15],
        [ 5]])

This can also be done with complex vectors:

In [4]:
# Define the ket-vectors as 2x1 column matrices:
ket_psi = np.matrix([[2-1j], 
                     [3j]])

ket_phi = np.matrix([[-3], 
                     [4-2j]])

# Compute their Kronecker product
np.kron(ket_psi, ket_phi)

matrix([[-6. +3.j],
        [ 6. -8.j],
        [-0. -9.j],
        [ 6.+12.j]])

Here is a more complicated example with two vectors of different dimensions:

\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes 
\begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix} = 
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix} \\
a_2 \begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_1b_3 \\ a_2b_1 \\ a_2b_2 \\ a_2b_3
\end{pmatrix}
\end{align}

Here is a corresponding numerical example:

\begin{align}
\begin{pmatrix}
1 \\ 4
\end{pmatrix} \otimes 
\begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix} = 
\begin{pmatrix}
1 \begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix} \\
4 \begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
5 \\ 2 \\ 4 \\ 20 \\ 8 \\ 16
\end{pmatrix}
\end{align} 

Here is the code for computing this tensor product:

In [5]:
ket_X = np.matrix([[1], 
                   [4]])

ket_Y = np.matrix([[5], 
                   [2], 
                   [4]])

np.kron(ket_X, ket_Y)

matrix([[ 5],
        [ 2],
        [ 4],
        [20],
        [ 8],
        [16]])

## Exercises

1. Using the following rule, 
\begin{align}
\begin{pmatrix}
a_1 \\ a_2 \\ a_3
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} = 
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_2\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_3\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_2b_1 \\ a_2b_2 \\ a_3b_1 \\ a_3b_2
\end{pmatrix}
\end{align}

compute the following tensor/Kroneckar product by hand:

\begin{align}
\begin{pmatrix}
2 \\ 7 \\ 3
\end{pmatrix} \otimes
\begin{pmatrix}
5 \\ 9
\end{pmatrix}
\end{align}

2. Write Python code to compute the above computation using the 'np.kron()' function. Remember to define two column (ket) vectors as matrices first.  

3. Derive a general rule for the following tensor product by performing the tensor product inside the parenthesis first:

\begin{align}
\left( \begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes 
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}\right) \otimes 
\begin{pmatrix}
c_1 \\ c_2
\end{pmatrix}
\end{align}

4. Now derive a general rule for the following tensor product by performing the tensor product in the parenthesis first:

\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes 
\left( \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \otimes 
\begin{pmatrix}
c_1 \\ c_2
\end{pmatrix}\right)
\end{align}

Convince yourself that your results from the previous two computations are in fact equal.

In [6]:
# 2

v_1 = np.matrix([[2], 
                   [7], 
                   [3]])

v_2 = np.matrix([[5], 
                   [9]])

np.kron(v_1, v_2)

matrix([[10],
        [18],
        [35],
        [63],
        [15],
        [27]])

In [7]:
# 3

v_1 = np.matrix([[2], 
                   [5]])

v_2 = np.matrix([[7], 
                   [9]])

v_3 = np.matrix([[3], 
                   [8]])

result1 = np.kron(v_1, v_2)

print("result1=", result1)

result2 = np.kron(result1, v_3)

print("result2=", result2)


result1= [[14]
 [18]
 [35]
 [45]]
result2= [[ 42]
 [112]
 [ 54]
 [144]
 [105]
 [280]
 [135]
 [360]]


In [8]:
# 4

v_1 = np.matrix([[2], 
                   [5]])

v_2 = np.matrix([[7], 
                   [9]])

v_3 = np.matrix([[3], 
                   [8]])

result1 = np.kron(v_2, v_3)

print("result1=", result1)

result2 = np.kron(v_1, result1)

print("result2=", result2)


result1= [[21]
 [56]
 [27]
 [72]]
result2= [[ 42]
 [112]
 [ 54]
 [144]
 [105]
 [280]
 [135]
 [360]]
